### PR TITLE
Added null check to stacktrace

### PR DESCRIPTION
**Pull request by AnderssonPeter**

### CODE REVIEW

**Comment by AnderssonPeter** [comment]
Hi there, is there any chance you could do a new release with this fix?

**Comment by mishamyte** [comment]
Hi!

I hope this weekend. Seems like this project is covered by dust a little. Will do a housekeeping & do a release

**Comment by mishamyte** [comment]
BTW, Small update from me. I almost done with all CI and pipelines and will push the package soon

**Comment by AnderssonPeter** [comment]
Thanks!

**Pull request merged**
